name: terraform-dev
run-name: Terraform Dev Testing
on: 
  workflow_dispatch: {}
  
env:
  ACCESS_KEY: ${{ secrets.AccessKey }}
  SECRET_KEY: ${{ secrets.SecretKey }}
jobs:
  terraform-dev-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install terraform
          export AWS_ACCESS_KEY_ID="$ACCESS_KEY"
          export AWS_SECRET_ACCESS_KEY="$SECRET_KEY"
      - name: Install tflocal
        run: pip install terraform-local
      - name: Initialize the Terraform Configuration
        run: tflocal init --var-file dev.tfvars
      - name: Validate Terraform Configuration
        run: tflocal validate 
      - name: Run Terraform Plan
        run: tflocal plan --var-file dev.tfvars
      - name: Run Terraform Apply
        run: tflocal apply -auto-approve --var-file dev.tfvars
